settings:
  name: "SolidFire Active IQ"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: NetApp Solidfire Active IQ documentation
      url: /index.html
      entries:
        - title: Get started with Solidfire Active IQ
          entries:
            - title: Overview
              url: /task_active_iq_get_started_overview.html
            - title: Enable SolidFire Active IQ reporting
              url: /task_active_iq_enable_reporting.html
            - title: Use the Active IQ UI
              url: /task_active_iq_use_the_user_interface.html
        - title: All Clusters View
          entries:
            - title: Overview
              url: /task_active_iq_all_clusters_view_overview.html
            - title: All Clusters View Dashboard
              url: /task_active_iq_all_clusters_view_dashboard.html
            - title: Alerts
              url: /task_active_iq_alerts.html
            - title: Capacity Licensing
              url: /task_active_iq_capacity_licensing.html
        - title: Nodes
          entries:
            - title: Overview
              url: /task_active_iq_nodes_overview.html
            - title: View SolidFire storage node details
              url: /task_active_iq_view_solidfire_node_details.html
            - title: View NetApp HCI storage and compute node details
              url: /task_active_iq_view_hci_node_details.html
homepage:
  tiles:
    - title: Work with SolidFire Active IQ
      links:
        - title: Get started
          url: /get_started_with_sf_active_iq.html
        - title: All Cluster View details
          url: /task_active_iq_all_clusters_view_overview.html
        - title: SolidFire and NetApp HCI node details
          url: /task_active_iq_nodes_overview.html
    - title: Troubleshoot
      links:
        - title: Troubleshoot
          url: /troubleshoot.html
        - title: Contact technical support
          url: https://mysupport.netapp.com/site/global/dashboard
