settings:
  name: "SolidFire Active IQ"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: NetApp Solidfire Active IQ documentation
      url: /index.html
      entries:
        - title: Get started with Solidfire Active IQ
          entries:
            - title: Overview
              url: /task-active-iq-get-started-overview.html
            - title: Enable SolidFire Active IQ reporting
              url: /task-active-iq-enable-reporting.html
            - title: Use the Active IQ UI
              url: /task-active-iq-use-the-user-interface.html
        - title: All Clusters View
          entries:
            - title: Overview
              url: /task-active-iq-all-clusters-view-overview.html
            - title: All Clusters View Dashboard
              url: /task-active-iq-all-clusters-view-dashboard.html
            - title: Alerts
              url: /task-active-iq-alerts.html
            - title: Capacity Licensing
              url: /task-active-iq-capacity-licensing.html
        - title: Select a cluster view
          entries:
            - title: Overview
              url: /task-active-iq-select-cluster-view-overview.html
            - title: Dashboard in Single Cluster view
              url: /task-active-iq-dashboard-in-single-cluster-view.html
            - title: Reporting options
              url: /task-active-iq-reporting-options-overview.html
        - title: Nodes
          entries:
            - title: Overview
              url: /task-active-iq-nodes-overview.html
            - title: View SolidFire storage node details
              url: /task-active-iq-view-solidfire-node-details.html
            - title: View NetApp HCI storage and compute node details
              url: /task-active-iq-view-hci-node-details.html
homepage:
  tiles:
    - title: Work with SolidFire Active IQ
      links:
        - title: Get started
          url: /get-started-with-sf-active-iq.html
        - title: All Cluster View details
          url: /task-active-iq-all-clusters-view_overview.html
        - title: SolidFire and NetApp HCI node details
          url: /task-active-iq-nodes-overview.html
    - title: Troubleshoot
      links:
        - title: Troubleshoot
          url: /troubleshoot.html
        - title: Contact technical support
          url: https://mysupport.netapp.com/site/global/dashboard
