settings:
  name: "SolidFire Active IQ"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: NetApp SolidFire Active IQ
      url: /index.html
    - title: Get started with SolidFire Active IQ
      entries:
        - title: Overview
          url: /task-active-iq-get-started-overview.html
        - title: Learn about SolidFire Active IQ
          url: /concept-active-iq-learn-about-active-iq.html
        - title: Enable SolidFire Active IQ reporting
          url: /task-active-iq-enable-reporting.html
        - title: Use the SolidFire Active IQ UI
          url: /task-active-iq-use-the-user-interface.html
    - title: Manage SolidFire Active IQ
      entries:
        - title: Overview
          url: /task-active-iq-manage-overview.html
        - title: All Clusters View
          entries:
            - title: Overview
              url: /task-active-iq-all-clusters-view-overview.html
            - title: All Clusters View Dashboard
              entries:
                - title: Dashboard
                  url: /task-active-iq-all-clusters-view-dashboard.html
                - title: Cluster Actions
                  url: /task-active-iq-cluster-options.html
            - title: Alerts
              url: /task-active-iq-alerts.html
            - title: Capacity Licensing
              url: /task-active-iq-capacity-licensing.html
            - title: Term Capacity
              url: /task-active-iq-term-capacity.html
        - title: Select a cluster
          entries:
            - title: Overview
              url: /task-active-iq-select-cluster-overview.html
            - title: Single cluster view dashboard
              url: /task-active-iq-single-cluster-view-dashboard.html
            - title: Reporting
              url: /task-active-iq-reporting-options.html
        - title: Nodes
          url: /task-active-iq-nodes.html
        - title: Drives
          url: /task-active-iq-drives.html
        - title: Volumes
          entries:
            - title: Overview
              url: /task-active-iq-volumes-overview.html
            - title: Active Volumes
              url: /task-active-iq-active-volumes.html
            - title: Snapshots and Snapshot Schedules
              url: /task-active-iq-snapshots-and-schedules.html
            - title: Volume Performance
              url: /task-active-iq-volume-performance.html
        - title: Replication
          url: /task-active-iq-replication.html
        - title: Virtual Volumes
          url: /task-active-iq-virtual-volumes.html
        - title: QoS Management
          entries:
            - title: Overview
              url: /task-active-iq-qos-management-overview.html
            - title: Recommendations
              url: /task-active-iq-recommendations.html
            - title: Node Throttling
              url: /task-active-iq-throttling.html
            - title: Busiest Volumes
              url: /task-active-iq-busiest-volumes.html
        - title: Virtual Machines
          url: /task-active-iq-virtual-machines.html
        - title: VMware Alarms
          url: /task-active-iq-vmware-alarms.html
        - title: All Nodes View
          url: /task-active-iq-all-nodes-view.html
    - title: Troubleshoot and support
      url: /task-active-iq-troubleshoot-support.html
    - title: Legal-notices
      url: /legal-notices.html