settings:
  name: "SolidFire Active IQ"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: NetApp Solidfire Active IQ documentation
      url: /index.html
      entries:
        - title: Get started with Solidfire Active IQ
          entries:
            - title: Overview
              url: /task-active-iq-get-started-overview.html
            - title: Enable SolidFire Active IQ reporting
              url: /task-active-iq-enable-reporting.html
            - title: Use the Active IQ UI
              url: /task-active-iq-use-the-user-interface.html
        - title: Manage SolidFire Active IQ
          entries:
            - title: Overview
              url: /task-active-iq-manage-overview.html
            - title: All Clusters View
              entries:
                - title: Overview
                  url: /task-active-iq-all-clusters-view-overview.html
                - title: All Clusters View Dashboard
                  url: /task-active-iq-all-clusters-view-dashboard.html
                - title: Alerts
                  url: /task-active-iq-alerts.html
                - title: Capacity Licensing
                  url: /task-active-iq-capacity-licensing.html
            - title: Select a Cluster
              entries:
                - title: Overview
                  url: /task-active-iq-select-cluster-overview.html
                - title: Dashboard in Single Cluster view
                  url: /task-active-iq-dashboard-in-single-cluster-view.html
                - title: Reporting options for a selected cluster
                  url: /task-active-iq-reporting-options.html
            - title: Nodes
              url: /task-active-iq-nodes.html
            - title: Drives
              url: /task_active_iq_drives.html
            - title: Volumes
              entries:
                - title: Overview
                  url: /task_active_iq_volumes_overview.html
                - title: Active volumes details
                  url: /task-active-iq-active-volumes-details.html
                - title: Snapshot copy details and schedules
                  url: /task-active-iq-view-snapshots-and-schedules.html
            - title: Replication
              url: /task_active_iq_replication.html
            - title: Virtual Volumes
              url: /task-active-iq-virtual-volumes.html
            - title: QoS Recommendations
              url: /task-active-iq-qos-recommendations.html
            - title: Virtual Machines
              url: /task-active-iq-virtual-machines.html
        - title: Troubleshoot and support
          url: /task-active-iq-troubleshoot-support.html
homepage:
  tiles:
    - title: Use the SolidFire Active IQ tool
      links:
        - title: Get started
          url: /task-active-iq-get-started-overview.html
        - title: Manage SolidFire Active IQ
          url: /task-active-iq-manage-overview.html
    - title: Product documentation
      links:
        - title: SolidFire and Element Software
          url: https://docs.netapp.com/us-en/element-software/index.html
        - title: NetApp HCI
          url: https://docs.netapp.com/us-en/hci/index.html
        - title: NetApp Product Documentation
          url: https://www.netapp.com/support-and-training/documentation
    - title: Troubleshoot
      links:
        - title: Troubleshoot
          url: /task-active-iq-troubleshoot-support.html
        - title: Contact technical support
          url: https://mysupport.netapp.com/site/global/dashboard
