---
permalink: task-active-iq-capacity-licensing.html
sidebar: sidebar
keywords: solidfire, active, iq, capacity, licensing
summary: 'Learn about the Capacity Licensing page in SolidFire Active IQ.'
---

= Capacity Licensing
:icons: font
:imagesdir: ./media/

[.lead]
On the *Capacity Licensing* page within the *All Clusters View*, you can view information about the NetApp Capacity Licensing model. Customers using standard SolidFire appliances should disregard this page.

To see a given capacity licensing pool you need permissions to view all clusters included in that pool. For cases where there are parent and child company relationships involved, please work with your account manager to ensure this is properly recorded, as failure to do so might render the capacity licensing pool as not visible.

Capacity Licensing is an alternative licensing option available from NetApp. Learn about or perform capacity licensing related tasks:

[cols=2*,options="header",cols="25,75"]
|===
|Heading |Description
|Pool Name |Name of the customer associated with the license.
|Entitled Capacity |Sum of software capacity licenses purchased.
|Provisioned Capacity |Amount of allocated provisioned capacity on all capacity licensed nodes in a customer environment.
|Used Capacity |Current used capacity by all clusters in a cluster pool.
|Clusters |Number of clusters and their IDs, which comprise a cluster pool for a license.
|===

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]

// 2023-03-15, DOC-4170