---
permalink: task-active-iq-enable-reporting.html
sidebar: sidebar
keywords: solidfire, active, iq, enable, reporting
summary: 'Learn about enabling SolidFire Active IQ reporting capability on the management node.'
---

= Enable SolidFire Active IQ reporting
:icons: font
:imagesdir: ./media/

[.lead]
You must enable SolidFire Active IQ reporting capability on the management node, if you did not already do so during installation or upgrade, before the Active IQ server can receive data payloads for a cluster from the management node. When the connection has been successfully set up, the cluster sends information to the Active IQ server. You can then view the cluster in the Active IQ UI, which displays cluster information.

NOTE: Google Chrome and Firefox browsers are supported to run with Active IQ.

.Before you begin
* Some functions in Active IQ, for example, quality of service (QoS), require Element 11.3 or later to work correctly. To confirm that you have the capability to use all Active IQ functions, NetApp recommends the following:
** Your storage cluster is running NetApp Element software 11.3 or later.
** You have deployed a management node running version 11.3 or later.
* You have internet access. You cannot use the Active IQ collector service from dark sites that do not have external connectivity.

.Steps
. Get the base asset ID for the installation:
.. Open the inventory service REST API UI on the management node:
+
----
https://<ManagementNodeIP>/inventory/1/
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the window.
.. From the REST API UI, select *GET ​/installations*.
.. Select *Try it out*.
.. Select *Execute*.
.. From the code 200 response body, copy the `id` for the installation.
+
[subs=+quotes]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+
NOTE: Your installation has a base asset configuration that was created during installation or upgrade.

. Activate telemetry:
.. Access the mnode service API UI on the management node by entering the management node IP address followed by `/mnode`:
+
----
https://<ManagementNodeIP>/mnode
----

.. Select *Authorize* or any lock icon and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the window.
.. Configure the base asset:
... Select *PUT /assets/{asset_id}*.
... Select *Try it out*.
... Enter the following in the JSON payload:
+
----
{
"telemetry_active": true
"config": {}
}
----
... Enter the base ID from the previous step in *asset_ID*.
... Select *Execute*.
+
The Active IQ service is automatically restarted whenever assets are changed. Modifying assets results in a short delay before settings are applied.

. Log in to link:https://activeiq.solidfire.com/[SolidFire Active IQ^] and confirm that you can view your clusters.
// https://raw.githubusercontent.com/NetAppDocs/element-software/main/_include/enable_active_iq.adoc[]

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]
