---
permalink: task-active-iq-active-volumes.html
sidebar: sidebar
keywords: solidfire, active, iq, active, volumes
summary: 'Learn about viewing volume details in SolidFire Active IQ.'
---
= Active Volumes
:icons: font
:imagesdir: ./media/

[.lead]
From the *Volumes* page, you can view details about active volumes.

== View active volume details
On the *Volumes* > *Active Volumes* page for a selected cluster, you can view the following information in the list of active volumes.

[cols=2*,options="header",cols="25,75"]
|===
|Heading	|Description

|ID	|ID given when the volume was created.
|Account ID |ID of the account assigned to the volume.
|Volume Size |Size of the volume from which the snapshot was created.
|Used Capacity a|Current used capacity of the volume:

* Green = up to 80%
* Yellow = above 80%
* Red = above 95%
|Primary Node ID |Primary node for this volume.
|Secondary Node ID |List of secondary nodes for this volume. Can be multiple values during transitory states, like change of secondary nodes, but will usually have a single value.
|QoS Throttle	a|Represents the current throttling for the volume. 

* Green = up to 20%
* Yellow = above 20%
* Red = above 80%

The value does not include historical throttling on the volume. 
|Min IOPS	|The minimum number of IOPS guaranteed for the volume.
|Max IOPS	|The maximum number of IOPS allowed for the volume.
|Burst IOPS	|The maximum number of IOPS allowed over a short period of time.
|Average IOPS Last 30 mins |The average number of IOPS executed for all volumes that have this node as their primary.

IOPS are collected over 500 millisecond intervals on the cluster side. SolidFire Active IQ collects these values at 60 second intervals. For each volume, the average IOPS is calculated from the SolidFire Active IQ values collected in the last 30 minutes.
|Average Throughput Last 30 mins |The average throughput executed for all volumes that have this node as their primary.

Throughput is collected over 500 millisecond intervals on the cluster side. SolidFire Active IQ collects these values at 60 second intervals. For each volume, the average throughput is calculated from the SolidFire Active IQ values collected in the last 30 minutes.
|Average Latency (µs) Last 30 min |The average time in microseconds to complete read and write operations to all volumes that have this node as their primary.

Latency is measured over 500 millisecond intervals on the cluster side. SolidFire Active IQ collects these values at 60 second intervals. For each volume, the average latency is calculated from the SolidFire Active IQ values collected in the last 30 minutes. For more information, see this https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/How_is_read_and_write_latency_measured_in_Element_Software_%3F[KB article^].
|Snapshots |The number of snapshots created for the volume.
|Actions |Select the vertical drop-down menu for more details on an individual volume.
|IOPS Rebalancing |Beginning with Element 12.8 clusters, an additional field *IOPS Rebalancing* is provided. If the cluster-wide option is enabled, then each volume shows this parameter. This field's value is either true or false. This field is used to balance slices according to the true load rather than the minimum IOPS settings.
|===

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]


// 2023 JULY 12, DOC-4697