---
permalink: task_active_iq_replication.html
sidebar: sidebar
keywords: solidfire, active, iq, replication
summary: 'Learn about the Replication page in SolidFire Active IQ.'
---

= Replication
:icons: font
:imagesdir: ./media/

[.lead]
The *Replication* page, available from the side panel for a selected cluster, provides information about cluster pairs and volumes pairs.

Learn more about the cluster pairs and volumes pairs pages:

* <<cluster_pairs,Cluster Pairs>>
* <<volume_pairs,Volume Pairs>>
* <<snapmirror_endpoints,SnapMirror Endpoints>>
* <<snapmirror_relationships,SnapMirror Relationships>>

[[cluster_pairs]]
== Cluster Pairs
On the *Replication* > *Cluster Pairs* page for a selected cluster, you can view the following information about cluster pairs.

[cols=2*,options="header",cols="30,70"]
|===
|Heading	|Description
|Cluster Pair ID |ID number given when the cluster pair was created.
|Remote Cluster Name |Name of the remote cluster of the pair.
|Remote MVIP |Management Virtual IP of the remote cluster.
|Replicating Volumes |Represents the number of volumes that are replicated on the paired cluster.
|Status	|State of the cluster pair.
|UUID	|Universally unique identifier.
|===

[[volume_pairs]]
== Volume Pairs
On the *Replication* > *Volume Pairs* page for a selected cluster, you can view the following information about volume pairs.

[cols=2*,options="header",cols="30,70"]
|===
|Heading	|Description
|Volume ID |ID number given when the volume was created.
|Account ID	|ID of the account assigned to the volume.
|Volume Status |State of the replicating volume.
|Replication Mode	|Type of mode selected for the volume pair.
|Direction a|Indicates the direction of the volume data:

* Source: indicates data is being written to a target outside the cluster.
* Target: indicates data is being written to the local volume from an outside source.
|Async Delay
a|
Length of time since the volume was last synced with the remote cluster. If the volume is not paired, this is null.

NOTE: A target volume in an active replication state always has an Async Delay of 0 (zero). Target volumes are system-aware during replication and assume async delay is accurate at all times.

|Remote Cluster	|Name of the remote cluster on which the volume resides.
|Remote Volume ID	|Volume ID of the volume on the remote cluster.
|===

[[snapmirror_endpoints]]
== SnapMirror Endpoints
On the *Replication* > *SnapMirror Endpoints* page for a selected cluster, you can view the following information about SnapMirror endpoints.

[cols=2*,options="header",cols="30,70"]
|===
|Heading	|Description
|Endpoint ID |The endpoint identification number.
|Remote Cluster Name |Name of the remote cluster of the pair.
|Cluster Management IP |Cluster management IP address.
|IPs |The range of virtual network IP addresses used for the virtual network.
|Relationships	|The number of relationships configured for an endpoint.
|Status	|This refers to whether or not the endpoint is currently connected. It has a value of "Connected" or "Disconnected".
|===

[[snapmirror_relationships]]
== SnapMirror Relationships
On the *Replication* > *SnapMirror Relationships* page for a selected cluster, you can view the following information about SnapMirror relationships.

[cols=2*,options="header",cols="30,70"]
|===
|Heading	|Description
|Endpoint ID |The endpoint identification number.
|Source Volume |The volume ID of the source.
|Destination Cluster |The name of the destination cluster in the SnapMirror relationship.
|Destination Volume |The name of the destination volume in the SnapMirror relationship.
|State	a|The state of the mirror relationship. It can have three possible values:

* Uninitialized: The destination volume isn't initialized.
* Snapmirrored: The destination volume is initialized and is ready to receive SnapMirror updates.
* Broken-off: The destination volume is in a read-write state and snapshots are present. 

|Status
a|
If the relationship is currently healthy. It can have values of "Healthy" or "Unhealthy"

NOTE: A value of "Unhealthy" might be caused by a manual or scheduled update failing or being aborted, or by the last scheduled update being delayed. The "Details" field following the status gives a description of the reason for the "Unhealthy" status.

|Relationship Type 
a|
The type of SnapMirror relationship. 

NOTE: On SolidFire systems this is always set to extended_data_protection. NetApp systems have other types of valid relationships that do not apply in the case of SolidFire systems.

|State a|The status of the cluster:

* Healthy: The cluster has no critical errors associated with it.
* Offline: The cluster cannot be accessed. Select the link to view the Error Log.
* Fault: There are errors associated with this cluster. Select the link to view the Error Log.

|Details | Information that helps identify the SnapMirror relationship.
|===

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]

https://docs.netapp.com/us-en/ontap/element-replication/index.html[Replication between NetApp Element software and ONTAP^]

// DOC-4612, 2022-Nov
// DOC-4612, 2023-Feb-03
// DOC-4612, 2023-Feb-16