---
permalink: task_active_iq_get_started_overview.html
sidebar: sidebar
keywords: solidfire, active, iq, started
summary: 'Learn about getting started with SolidFire Active IQ.'
---

= Get started with SolidFire Active IQ
:icons: font
:imagesdir: ../media/

[.lead]
The SolidFire Active IQ tool makes monitoring, capacity, and performance, as well as being informed about cluster health, easy and accessible from anywhere. No matter how you use SolidFire Active IQ, there are several things to know before you start using it:

* link:task_active_iq_enable_reporting.html[Enable SolidFire Active IQ reporting]: You must enable the Active IQ reporting capability on the management node before the Active IQ server can connect to a cluster and receive cluster information.
* link:task_active_iq_use_the_user_interface.html[Use the SolidFire Active IQ UI]: Learn about the new or enhanced features such as filtering, sorting, exporting data, and cluster selection.

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]
