---
permalink: task_active_iq_drives.html
sidebar: sidebar
keywords: solidfire, active, iq, drives
summary: 'Learn about the Drives page in SolidFire Active IQ.'
---

= Drives
:icons: font
:imagesdir: ./media/

[.lead]
Each node contains one or more physical drives, which are used to store a portion of the data for the cluster. The cluster utilizes the capacity and performance of the drive after the drive is successfully added to a cluster.

On the *Drives* page, available from the side panel for a selected cluster, you can filter the page by selecting from the *Active*, *Available*, and *Failed* tabs.

The following information is available for each drive in the cluster depending on the state of drive functionality:

[cols=2*,options="header",cols="25,75"]
|===
|Heading |Description

|Drive ID	|Sequential number assigned to the drive.
|Node ID |Assigned node number when the node is added to the cluster.
|Service ID	|The current service ID of the block or slice service that is associated with the drive.
|Slot	|Slot number where the drive is physically located.
|Capacity	|Gigabyte size of the drive.
|Firmware version	|Version of the firmware on the drive.
|Serial	|Serial number of the SSD.
|Wear |Remaining	Wear level indicator.
|Reserve |Drive available reserves.
|Type |Drive type can be block or metadata.
|===

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]
