---
permalink: use_filters.html
sidebar: sidebar
keywords: solidfire, active, iq, started
summary: 'Learn about sorting and filtering list information on pages in Active IQ.'
---
= Use filters
:icons: font
:imagesdir: ../media/

[.lead]
You can sort and filter list information on pages in Active IQ. When viewing lists (such as nodes, drives, volumes, and so on), you can use the filter functionality to focus the information and make it more easily fit on the screen.

.Steps

. When viewing list information, select *Filter*.
. Choose a column name to filter by from the drop-down menu.
. Select a constraint for the column.
. Enter text to filter by.
. Select *Add Filter*.
+
The system runs the new filter on the information in the list and temporarily stores the new filter. The selected filter is shown at the bottom of the filter dialog box.

. (Optional) You can add another filter by performing the following steps:
.. Select another column heading and constraint.
.. Select *Add Filter*.
. (Optional) Select (*x*) to remove the filters and display the unfiltered list information.

NOTE: Some tables include the option to exclude columns from view. For best results, select *Columns* to ensure all required columns are showing when setting filters.

== Find more information
https://www.netapp.com/support-and-training/documentation/[NetApp Product Documentation^]
